### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by albertcito** [knicola/yup-password#2]
I'm getting this error when I write in the `current password` input, and the others are empty.

This is my schema:

```typescript
const schema = Yup.object().shape({
      old_password: Yup.string().required(),
      password: Yup.string().min(8)
        .minLowercase(1)
        .minUppercase(1)
        .minNumber(1)
        .required(),
      password_confirmation: Yup.string().oneOf([
        Yup.ref('password')], 'Passwords must match'),
    });
```

<img width="1247" alt="Screen Shot 2021-01-15 at 1 41 23 PM" src="https://user-images.githubusercontent.com/1768483/104765742-5cff8700-5737-11eb-8e70-972cec531645.png">
<img width="771" alt="Screen Shot 2021-01-15 at 1 42 37 PM" src="https://user-images.githubusercontent.com/1768483/104765839-8d472580-5737-11eb-9d5f-31efa2b2ba88.png">

**Comment by knicola** [comment]
thank you for reporting this. I've pushed out a new version. `undefined` values will now be considered valid and can be caught by using `required()`.
