### ISSUE TITLE
password() message

### ISSUE THREAD

**Issue by kgrigorian** [knicola/yup-password#7]
.password() method does not take message argument (other method do have it)

**Comment by knicola** [comment]
the `.password()` is mostly a convenience method, if you will, with reasonable defaults. it doesn't make much sense to me to add options to customize its behavior when you can either chain the rule you want to customize (ie `.password().minLowercase(1, 'custom message'`) or replace `.password()` completely with the rules you think is best for your use case.

however, if more people would like this option I will not object to it.

two variations come to mind:
```js
// 1st option
.password({
  messages: {
    minLowercase: 'custom message',
    minUppercase: 'custom message',
    ...
  },
  rules: {
    minLowercase: 2,
    minUppercase: 3,
    ...
  },
})
// 2nd option
.password({
  minLowercase: [2, 'custom message'],
  minUppercase: [2, 'custom message'],
  ..
})
```
also lets compare it to this:
```js
.password().minLowercase(2, 'custom message').minUppercase(3, 'custom message')
```

additional ideas are welcome

**Comment by knicola** [comment]
closing this ticket for now. if anyone thinks this is a useful option to have and/or have any additional ideas please drop them here and will reopen the ticket for discussion.

**Comment by MadhawaS96** [comment]
Just a tiny issue, maybe I missed this in the docs. Say I have a field name as "currentPassword". The returned error message would be displayed as ie: "currentPassword must contain at least 1 uppercase letter". 

Do you have any option to change the name set into the error message? I hope the description explains the issue clearly.

Let me know if you prefer this to be opened as a new issue. Tagged here since I thought this can be related to the current topic.

Thanks!

**Comment by knicola** [comment]
@MadhawaS96 you can use [Schema.label()](https://github.com/jquense/yup?tab=readme-ov-file#schemalabellabel-string-schema)

```js
const schema = yup.object().shape({
    currentPassword: yup.string().password().required().label('Current password'),
})
```

**Comment by MadhawaS96** [comment]
> @MadhawaS96 you can use [Schema.label()](https://github.com/jquense/yup?tab=readme-ov-file#schemalabellabel-string-schema)
> 
> ```js
> const schema = yup.object().shape({
>     currentPassword: yup.string().password().required().label('Current password'),
> })
> ```

Brilliant! Thank you so much for both the answer and your quick response. Much appreciated!
